# Generated by Django 5.1 on 2024-08-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abilities', models.CharField(max_length=255)),
                ('forms', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('stats', models.TextField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('image_url', models.URLField(max_length=255)),
            ],
        ),
    ]
